### ISSUE TITLE
Queue.__aiter__ finalisation is not safe

### ISSUE THREAD

**Issue by maxfischer2781** [MaineKuehn/usim#86]
**Description of the bug**
If ``Queue.__aiter__`` is closed via garbage collection, it still attempts to ``await``. Side-effects of this are implementation dependent.

**How To Reproduce**
No idea how to reproduce this. It seems that CPython silently swallows the ``await``, probably by replying ``None``. PyPy fails to close the iterator gracefully.

```
Exception ignored in: finalizer of <async generator object Queue.__aiter__ at 0x0000000107103b48>
Traceback (most recent call last):
  File "/usr/local/Cellar/pypy3/7.1.1_1/libexec/site-packages/usim/_basics/streams.py", line 168, in _await_message
    await self._notification
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/pypy3/7.1.1_1/libexec/site-packages/usim/_basics/streams.py", line 176, in __aiter__
    yield await self
  File "/usr/local/Cellar/pypy3/7.1.1_1/libexec/site-packages/usim/_basics/streams.py", line 158, in __await__
    return (yield from self._await_message().__await__())  # noqa: B901
  File "/usr/local/Cellar/pypy3/7.1.1_1/libexec/site-packages/usim/_basics/streams.py", line 171, in _await_message
    return self._buffer.popleft()
RuntimeError: PyPy limitation: cannot use 'yield from' or 'await' in a generator/coroutine that has been partially deallocated already, typically seen via __del__
```

**Expected behavior**
Deterministic cleanup on all platforms.

**Comment by maxfischer2781** [comment]
Minimal reproducible example:
```python3
import gc
from usim import Queue, run, Scope


async def fetch(queue):
    async for item in queue:
        pass


async def foo(queue: Queue):
    async with Scope() as scope:
        scope.do(fetch(queue), volatile=True)
    gc.collect()

run(foo(Queue()))
```

**Comment by maxfischer2781** [comment]
This appears to be related to having an exception handler wrapped around the internal ``yield`` of ``Queue.__aiter__``.
```python3

    async def __aiter__(self):
        while True:
            try:
                yield await self  # <<< here
            except StreamClosed:
                break
```

Moving the ``yield`` outside of the ``try:`` block removes the error:

```python3
    async def __aiter__(self):
        while True:
            try:
                result = await self
            except StreamClosed:
                break
            else:
                yield result
```

Not sure if that also removes the observed side-effects. MCVE does not replicate them yet.

**Comment by maxfischer2781** [comment]
The underlying limitation is apparently [removed in PyPy 3.7](https://bitbucket.org/pypy/pypy/commits/c2f8aa002dda1332b57b1eacc3c56f6fd5d279f6).
